### ISSUE TITLE
Latest 1.0.23 migration update fails

### ISSUE THREAD

**Issue by CodyMcMichael** [Dolphiq/craft-plugin-redirect#91]
Craft Version: 3.0.41.1
Postgres Version: 9.6

Hey I'm updating an existing app that has existing redirect data. Whenever I try to update the plugin to `1.0.23`, the migration fails and logs this from my container.

```
cg-postgres | ERROR:  syntax error at or near "NOT" at character 77
cg-postgres | STATEMENT:  ALTER TABLE "dolphiq_redirects" ALTER COLUMN "sourceUrl" TYPE varchar(1000) NOT NULL DEFAULT ''
```

I bumped back to `1.0.20` which seems to be the latest stable version for now and everything works as expected. Just thought you would like to know. Thanks

**Comment by peimansh** [comment]
Exactly same issue here.
Output Log from migration failure:
```
Database Exception: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "NOT"
LINE 1: ...ects" ALTER COLUMN "sourceUrl" TYPE varchar(1000) NOT NULL D...
^
The SQL being executed was: ALTER TABLE "craft_dolphiq_redirects" ALTER COLUMN "sourceUrl" TYPE varchar(1000) NOT NULL DEFAULT ''

Migration: dolphiq\redirect\migrations\m190426_121317_change_url_size_to_1000

Output:

> alter column sourceUrl in table {{%dolphiq_redirects}} to string(1000) NOT NULL DEFAULT '' ...Exception: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "NOT"
LINE 1: ...ects" ALTER COLUMN "sourceUrl" TYPE varchar(1000) NOT NULL D...
^
The SQL being executed was: ALTER TABLE "craft_dolphiq_redirects" ALTER COLUMN "sourceUrl" TYPE varchar(1000) NOT NULL DEFAULT '' (/var/www/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "cr...')
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE "cr...')
#2 /var/www/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /var/www/vendor/dolphiq/redirect/src/migrations/m190426_121317_change_url_size_to_1000.php(22): yii\db\Migration->alterColumn('{{%dolphiq_redi...', 'sourceUrl', Object(yii\db\ColumnSchemaBuilder))
#4 /var/www/vendor/craftcms/cms/src/db/Migration.php(56): dolphiq\redirect\migrations\m190426_121317_change_url_size_to_1000->safeUp()
...
```
Craft CMS version: 3.0.35
Postgres: 10.5
It happens when updating to 1.0.23
